// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package notify

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	NotifyFollow(ctx context.Context, in *NotificationRequest, opts ...grpc.CallOption) (*NotificationResponse, error)
	NotifyCreate(ctx context.Context, opts ...grpc.CallOption) (NotificationService_NotifyCreateClient, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) NotifyFollow(ctx context.Context, in *NotificationRequest, opts ...grpc.CallOption) (*NotificationResponse, error) {
	out := new(NotificationResponse)
	err := c.cc.Invoke(ctx, "/notify.NotificationService/NotifyFollow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) NotifyCreate(ctx context.Context, opts ...grpc.CallOption) (NotificationService_NotifyCreateClient, error) {
	stream, err := c.cc.NewStream(ctx, &NotificationService_ServiceDesc.Streams[0], "/notify.NotificationService/NotifyCreate", opts...)
	if err != nil {
		return nil, err
	}
	x := &notificationServiceNotifyCreateClient{stream}
	return x, nil
}

type NotificationService_NotifyCreateClient interface {
	Send(*NotificationRequest) error
	CloseAndRecv() (*NotificationResponse, error)
	grpc.ClientStream
}

type notificationServiceNotifyCreateClient struct {
	grpc.ClientStream
}

func (x *notificationServiceNotifyCreateClient) Send(m *NotificationRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *notificationServiceNotifyCreateClient) CloseAndRecv() (*NotificationResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(NotificationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility
type NotificationServiceServer interface {
	NotifyFollow(context.Context, *NotificationRequest) (*NotificationResponse, error)
	NotifyCreate(NotificationService_NotifyCreateServer) error
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (UnimplementedNotificationServiceServer) NotifyFollow(context.Context, *NotificationRequest) (*NotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyFollow not implemented")
}
func (UnimplementedNotificationServiceServer) NotifyCreate(NotificationService_NotifyCreateServer) error {
	return status.Errorf(codes.Unimplemented, "method NotifyCreate not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_NotifyFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).NotifyFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notify.NotificationService/NotifyFollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).NotifyFollow(ctx, req.(*NotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_NotifyCreate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NotificationServiceServer).NotifyCreate(&notificationServiceNotifyCreateServer{stream})
}

type NotificationService_NotifyCreateServer interface {
	SendAndClose(*NotificationResponse) error
	Recv() (*NotificationRequest, error)
	grpc.ServerStream
}

type notificationServiceNotifyCreateServer struct {
	grpc.ServerStream
}

func (x *notificationServiceNotifyCreateServer) SendAndClose(m *NotificationResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *notificationServiceNotifyCreateServer) Recv() (*NotificationRequest, error) {
	m := new(NotificationRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notify.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyFollow",
			Handler:    _NotificationService_NotifyFollow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NotifyCreate",
			Handler:       _NotificationService_NotifyCreate_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "notify/protos/notify.proto",
}
